Repository CambaSoft/WebApp, pull requests merged in 2021-10, with the labels that each got.

#5 calendly css and js added
  src/index.html
Labels: bug

#9 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement

#11 Update README.md
  README.md
Labels: documentation

#19 subdivisiones de filas
  src/app/app.module.ts
  src/app/compi/compi.component.css
  src/app/compi/compi.component.html
  src/app/compi/compi.component.spec.ts
  src/app/compi/compi.component.ts
  src/app/ed1/ed1.component.css
  src/app/ed1/ed1.component.html
  src/app/ed1/ed1.component.spec.ts
  src/app/ed1/ed1.component.ts
  src/app/ed2/ed2.component.css
  src/app/ed2/ed2.component.html
  src/app/ed2/ed2.component.spec.ts
  src/app/ed2/ed2.component.ts
  src/app/ensamblador/ensamblador.component.css
  src/app/ensamblador/ensamblador.component.html
  src/app/ensamblador/ensamblador.component.spec.ts
  src/app/ensamblador/ensamblador.component.ts
  src/app/fila1/fila1.component.html
  src/app/fila2/fila2.component.html
  src/app/fila3/fila3.component.html
  src/app/fila4/fila4.component.html
  src/app/program2/program2.component.css
  src/app/program2/program2.component.html
  src/app/program2/program2.component.spec.ts
  src/app/program2/program2.component.ts
  src/app/si1/si1.component.css
  src/app/si1/si1.component.html
  src/app/si1/si1.component.spec.ts
  src/app/si1/si1.component.ts
  src/app/si2/si2.component.css
  src/app/si2/si2.component.html
  src/app/si2/si2.component.spec.ts
  src/app/si2/si2.component.ts
  src/app/tecnoweb/tecnoweb.component.css
  src/app/tecnoweb/tecnoweb.component.html
  src/app/tecnoweb/tecnoweb.component.spec.ts
  src/app/tecnoweb/tecnoweb.component.ts
Labels: enhancement
